--CREATE TABLE public.users (
--    id BIGSERIAL PRIMARY KEY,
--    email VARCHAR,
--    password VARCHAR,
--    first_name VARCHAR,
--    last_name VARCHAR,
--    phone_number VARCHAR,
--    role VARCHAR,
--);